import React, { useState } from 'react';
import { usePlatform } from '../context/PlatformContext';
import { CfdLogo } from '../components/common/CfdLogo';
import {
  Rocket,
  LayoutDashboard,
  BookOpen,
  Microscope,
  Brain,
  FileSpreadsheet,
  ArrowRight,
  Sparkles,
  Zap,
  CheckCircle2,
  Wind,
  Cpu,
  Activity,
  Gauge,
  Maximize2,
  X,
  ExternalLink,
  Eye,
  Sliders,
  Layers,
  ChevronRight
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { sound } from '../utils/soundEffects';

interface AerodynamicStudy {
  id: string;
  title: string;
  category: string;
  regime: string;
  imageSrc: string;
  description: string;
  telemetry: {
    reynolds: string;
    mach: string;
    coefficients: string;
    solver: string;
  };
  highlights: string[];
}

const AERODYNAMIC_STUDIES: AerodynamicStudy[] = [
  {
    id: 'vehicle-wind-tunnel',
    title: 'Prototype Racecar Wind Tunnel Aerodynamics',
    category: 'Automotive Ground Effects',
    regime: 'Incompressible Turbulent (k-ω SST)',
    imageSrc: '/src/assets/images/cfd_wind_tunnel_vehicle_1790163836534.jpg',
    description: 'High-performance carbon fiber prototype vehicle inside a laser-illuminated wind tunnel. Multi-color particle streaklines illustrate boundary layer attachment along the cockpit and powerful vortex suction generated by the underbody ground-effect diffuser.',
    telemetry: {
      reynolds: 'Re = 4.8 × 10⁶',
      mach: 'M = 0.22 (75 m/s)',
      coefficients: 'Cd: 0.238 • Cl: -1.14',
      solver: 'OpenFOAM simpleFoam',
    },
    highlights: [
      'Underbody ground effect venturi acceleration',
      'Rear wing downforce vortex shedding',
      'Boundary layer separation delay at A-pillars',
      'Wheelturret wake turbulence attenuation'
    ]
  },
  {
    id: 'transonic-shockwave',
    title: 'Transonic Wing Lambda Shock Wave Formation',
    category: 'Aerospace High-Speed',
    regime: 'Compressible Navier-Stokes (Euler / RANS)',
    imageSrc: '/src/assets/images/cfd_transonic_shockwave_1790163852748.jpg',
    description: 'Real-time scientific visualization of a commercial airliner supercritical airfoil at cruise speed. As flow accelerates past the speed of sound over the upper camber, an intense normal shockwave forms, showing scalar pressure jumps and wave drag buildup.',
    telemetry: {
      reynolds: 'Re = 2.4 × 10⁷',
      mach: 'M = 0.85 Cruise',
      coefficients: 'Cl/Cd: 48.2 • AoA: +2.4°',
      solver: 'SU2 Transonic RANS',
    },
    highlights: [
      'Lambda (λ) shockwave boundary layer interaction',
      'Scalar pressure coefficient distribution (-Cp)',
      'Wave drag onset mitigation via supercritical camber',
      'Trailing edge buffeting prevention margin'
    ]
  },
  {
    id: 'propeller-vortex-wake',
    title: 'High-Twist Propeller Blade Helical Wake Vortices',
    category: 'Rotorcraft & Propulsion',
    regime: 'Unsteady Sliding Mesh (pimpleFoam)',
    imageSrc: '/src/assets/images/cfd_vortex_propeller_wake_1790163871792.jpg',
    description: 'Volumetric 3D scientific visualization of high-efficiency carbon-fiber drone propeller. Illuminated velocity vectors and Q-criterion isosurfaces reveal tight helical tip vortices shedding into the downstream slipstream.',
    telemetry: {
      reynolds: 'Re = 1.2 × 10⁵',
      mach: 'Tip M = 0.46',
      coefficients: 'Thrust: 42.6 N • FoM: 0.76',
      solver: 'OpenFOAM pimpleFoam',
    },
    highlights: [
      'Crisp helical vortex core tube visualization',
      'Tip vortex cavitation reduction geometry',
      'Acoustic noise signature pressure pulses',
      'Induced drag minimization by tip sweep'
    ]
  },
  {
    id: 'neural-flow-ai',
    title: 'Fourier Neural Operator (FNO) Real-Time Prediction',
    category: 'AI Physics Surrogate',
    regime: 'DeepONet / FNO Inversion (12ms Latency)',
    imageSrc: '/src/assets/images/cfd_neural_flow_ai_1790163889547.jpg',
    description: 'Translucent aerodynamic geometry embedded in neural network synaptic connection nodes. Physics-Informed Neural Networks predict complete 3D Navier-Stokes velocity and pressure fields in milliseconds with 98.4% OpenFOAM parity.',
    telemetry: {
      reynolds: 'Parametric Envelope',
      mach: '0.1 to 1.2 M',
      coefficients: 'Confidence: 98.4% • Δt: 12ms',
      solver: 'FNO + PINN Gemini Hybrid',
    },
    highlights: [
      'Sub-second inference vs 45-minute cluster run',
      'Continuous zero-shot mesh resolution invariance',
      'Real-time design space exploration for engineers',
      'Automated aerodynamic anomaly detection'
    ]
  }
];

export const LandingPage: React.FC = () => {
  const { setPage, setCurrentGeometryId } = usePlatform();
  const [selectedStudy, setSelectedStudy] = useState<AerodynamicStudy | null>(null);

  const handleStart = () => {
    sound.playClick();
    setPage('projects');
  };

  const handleDashboard = () => {
    sound.playClick();
    setPage('dashboard');
  };

  const handleDoc = () => {
    sound.playTick();
    setPage('setup');
  };

  const handleStudyInspect = (study: AerodynamicStudy) => {
    sound.playClick();
    setSelectedStudy(study);
  };

  const handleLaunchStudy = (study: AerodynamicStudy) => {
    sound.playSave();
    setSelectedStudy(null);
    if (study.id === 'vehicle-wind-tunnel') {
      setCurrentGeometryId('sample-fsae');
      setPage('geometry');
    } else if (study.id === 'propeller-vortex-wake') {
      setCurrentGeometryId('sample-propeller');
      setPage('geometry');
    } else if (study.id === 'neural-flow-ai') {
      setPage('ai');
    } else {
      setCurrentGeometryId('sample-airfoil');
      setPage('runner');
    }
  };

  return (
    <div className="flex-1 overflow-y-auto select-none text-slate-800 p-4 sm:p-6 lg:p-8 space-y-8">
      {/* Hero Container with High-Impact Aerodynamic Split Layout */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="relative overflow-hidden rounded-3xl p-6 sm:p-8 lg:p-10 bg-gradient-to-br from-[#0369A1] via-[#0284C7] to-[#0EA5E9] text-white shadow-2xl border border-white/20"
      >
        {/* Subtle decorative background wave SVG */}
        <div className="absolute inset-0 opacity-15 pointer-events-none">
          <svg className="w-full h-full" viewBox="0 0 1000 400" preserveAspectRatio="none">
            <path
              d="M0,150 C200,80 350,220 500,150 C650,80 800,200 1000,120 L1000,400 L0,400 Z"
              fill="white"
            />
          </svg>
        </div>

        <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          {/* Left Hero Column: Copy & Primary CTAs */}
          <div className="lg:col-span-6 space-y-4">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-white/20 backdrop-blur-md border border-white/30 text-xs font-semibold tracking-wider uppercase text-sky-100 shadow-xs">
              <Sparkles className="w-3.5 h-3.5 text-cyan-200 animate-pulse" />
              <span>OFFICIAL CFD AERODYNAMICS PLATFORM</span>
            </div>

            <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-white leading-tight font-sans">
              Real-World CFD <br />
              <span className="text-cyan-200">Wind Tunnel</span> Physics
            </h1>

            <p className="text-base sm:text-lg text-sky-100 font-semibold tracking-wide">
              High-Fidelity Aerodynamics • Navier-Stokes Solvers • AI Surrogates
            </p>

            <p className="text-xs sm:text-sm text-sky-100/90 leading-relaxed font-normal">
              Direct in-browser aerodynamic engineering workbench. Simulate compressible transonic flow, 
              turbulent boundary layers, ground effect vortex dynamics, and automated compliance reporting with real-world accuracy.
            </p>

            {/* Action CTAs */}
            <div className="flex flex-wrap items-center gap-3 pt-2">
              <button
                onClick={handleStart}
                className="min-h-[44px] flex items-center justify-center gap-2 px-5 py-2.5 bg-white hover:bg-sky-50 text-[#0369A1] rounded-xl font-bold text-sm shadow-md transition-all active:scale-95 cursor-pointer"
              >
                <Rocket className="w-4 h-4 text-[#0284C7]" />
                <span>Start Simulation</span>
              </button>

              <button
                onClick={handleDashboard}
                className="min-h-[44px] flex items-center justify-center gap-2 px-5 py-2.5 bg-white/20 hover:bg-white/30 text-white border border-white/40 rounded-xl font-semibold text-sm backdrop-blur-sm transition-all active:scale-95 cursor-pointer shadow-xs"
              >
                <LayoutDashboard className="w-4 h-4 text-cyan-200" />
                <span>Dashboard</span>
              </button>

              <button
                onClick={() => handleStudyInspect(AERODYNAMIC_STUDIES[0])}
                className="min-h-[44px] flex items-center justify-center gap-2 px-4 py-2.5 bg-cyan-400/25 hover:bg-cyan-400/35 text-white border border-cyan-300/40 rounded-xl font-semibold text-sm backdrop-blur-sm transition-all active:scale-95 cursor-pointer shadow-xs"
              >
                <Eye className="w-4 h-4 text-cyan-200" />
                <span>View Real Studies</span>
              </button>
            </div>

            {/* Live Metrics Quick Badges */}
            <div className="flex items-center gap-4 pt-3 text-[11px] text-sky-100 font-mono border-t border-white/20">
              <span className="flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                OpenFOAM v2606
              </span>
              <span>•</span>
              <span>SU2 Transonic RANS</span>
              <span>•</span>
              <span>Fourier Neural 12ms</span>
            </div>
          </div>

          {/* Right Hero Column: Real High-Definition 3D Aerodynamic Wing Render Showcase */}
          <div className="lg:col-span-6 flex justify-center">
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.12 }}
              onClick={() => handleStudyInspect(AERODYNAMIC_STUDIES[1])}
              className="group relative w-full rounded-2xl overflow-hidden shadow-2xl border-2 border-white/60 bg-slate-900 cursor-pointer"
            >
              {/* Real 3D CFD Render Asset */}
              <div className="relative aspect-video w-full overflow-hidden bg-slate-950">
                <img
                  src="/src/assets/images/cfd_hero_aerodynamic_render_1790163821497.jpg"
                  alt="High-Fidelity 3D CFD Wind Tunnel Aerodynamic Wing Simulation"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  referrerPolicy="no-referrer"
                />

                {/* Subtle soft gradient scrim for readable telemetry */}
                <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-slate-950/40" />

                {/* Top Badge Overlay */}
                <div className="absolute top-3 left-3 right-3 flex items-center justify-between">
                  <div className="flex items-center gap-2 px-2.5 py-1 rounded-full bg-slate-900/80 backdrop-blur-md border border-white/30 text-[10px] font-mono font-bold text-white shadow-md">
                    <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                    <span>REAL CFD GRAPHIC • 3D STREAMLINES</span>
                  </div>

                  <div className="flex items-center gap-1 px-2 py-1 rounded-md bg-white/20 hover:bg-white/30 text-white backdrop-blur-md text-[10px] font-semibold border border-white/30 transition-colors">
                    <Maximize2 className="w-3 h-3" />
                    <span>Inspect</span>
                  </div>
                </div>

                {/* Bottom Aerodynamic HUD Telemetry Overlay */}
                <div className="absolute bottom-3 left-3 right-3 p-3 rounded-xl bg-slate-900/85 backdrop-blur-md border border-white/20 text-white space-y-1.5 shadow-lg">
                  <div className="flex items-center justify-between text-xs font-bold">
                    <span className="text-cyan-300">Supersonic Wing Pressure Field</span>
                    <span className="text-amber-400 font-mono">Mach 0.85 Cruise</span>
                  </div>
                  <div className="flex items-center justify-between text-[10px] font-mono text-slate-300">
                    <span>Re: 4.8×10⁶ • k-ω SST Boundary Layer</span>
                    <span className="text-emerald-400 font-bold">Cd: 0.021 • Cl: 0.542</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </motion.div>

      {/* Real Aerodynamic Telemetry Strip */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.08 }}
        className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3.5 rounded-2xl bg-white/95 backdrop-blur-xl border border-sky-300/80 shadow-lg text-slate-800"
      >
        <div className="flex items-center gap-3 p-2.5 rounded-xl bg-sky-50 border border-sky-200">
          <div className="w-9 h-9 rounded-lg bg-sky-500/20 text-sky-700 flex items-center justify-center shrink-0">
            <Wind className="w-5 h-5 text-sky-600" />
          </div>
          <div className="min-w-0">
            <div className="text-[10px] text-slate-500 font-medium truncate">Streamline Velocity</div>
            <div className="text-xs font-bold text-sky-800 font-mono flex items-center gap-1">
              <span>75 m/s Inflow</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping" />
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3 p-2.5 rounded-xl bg-cyan-50 border border-cyan-200">
          <div className="w-9 h-9 rounded-lg bg-cyan-500/20 text-cyan-700 flex items-center justify-center shrink-0">
            <Gauge className="w-5 h-5 text-cyan-600" />
          </div>
          <div className="min-w-0">
            <div className="text-[10px] text-slate-500 font-medium truncate">Reynolds Regime</div>
            <div className="text-xs font-bold text-cyan-800 font-mono truncate">
              Re: 4.8×10⁶ Turbulent
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3 p-2.5 rounded-xl bg-amber-50 border border-amber-200">
          <div className="w-9 h-9 rounded-lg bg-amber-500/20 text-amber-700 flex items-center justify-center shrink-0">
            <Activity className="w-5 h-5 text-amber-600" />
          </div>
          <div className="min-w-0">
            <div className="text-[10px] text-slate-500 font-medium truncate">Boundary Layer Wake</div>
            <div className="text-xs font-bold text-amber-800 font-mono truncate">
              Cd: 0.238 • Attached
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3 p-2.5 rounded-xl bg-emerald-50 border border-emerald-200">
          <div className="w-9 h-9 rounded-lg bg-emerald-500/20 text-emerald-700 flex items-center justify-center shrink-0">
            <Cpu className="w-5 h-5 text-emerald-600" />
          </div>
          <div className="min-w-0">
            <div className="text-[10px] text-slate-500 font-medium truncate">Acceleration Engine</div>
            <div className="text-xs font-bold text-emerald-800 font-mono truncate">
              OpenFOAM + FNO (12ms)
            </div>
          </div>
        </div>
      </motion.div>

      {/* NEW FEATURE SECTION: Real Aerodynamics Graphics & Simulation Studies Showcase */}
      <section className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-1">
          <div>
            <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-sky-700 mb-0.5">
              <Layers className="w-3.5 h-3.5 text-sky-600" />
              <span>Real Physics Graphics Showcase</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
              Real Aerodynamic Studies & Visualizations
            </h2>
            <p className="text-xs sm:text-sm text-slate-600">
              Explore photorealistic CFD flow fields, wind tunnel smoke streams, shockwave diffraction, and tip vortex physics.
            </p>
          </div>

          <button
            onClick={() => handleStudyInspect(AERODYNAMIC_STUDIES[0])}
            className="self-start sm:self-center flex items-center gap-1.5 px-3.5 py-1.5 bg-sky-50 hover:bg-sky-100 text-sky-700 border border-sky-300 rounded-xl text-xs font-bold transition-colors cursor-pointer shadow-2xs"
          >
            <span>Interactive Gallery</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* 4 Rich Real Graphic Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          {AERODYNAMIC_STUDIES.map((study, idx) => (
            <motion.div
              key={study.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35, delay: idx * 0.08 }}
              onClick={() => handleStudyInspect(study)}
              className="group card-bright hover:shadow-xl hover:border-sky-400 rounded-2xl overflow-hidden border border-sky-200 transition-all duration-300 flex flex-col justify-between cursor-pointer bg-white"
            >
              <div>
                {/* Real Graphic Image Slot */}
                <div className="relative aspect-4/3 w-full overflow-hidden bg-slate-900">
                  <img
                    src={study.imageSrc}
                    alt={study.title}
                    className="w-full h-full object-cover group-hover:scale-108 transition-transform duration-500"
                    referrerPolicy="no-referrer"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 via-transparent to-transparent opacity-60 group-hover:opacity-40 transition-opacity" />

                  {/* Regime Tag */}
                  <div className="absolute top-2.5 left-2.5">
                    <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-md bg-slate-900/80 text-cyan-300 border border-cyan-500/30 backdrop-blur-md">
                      {study.category}
                    </span>
                  </div>

                  {/* Hover Inspect Indicator */}
                  <div className="absolute bottom-2.5 right-2.5 opacity-0 group-hover:opacity-100 transition-opacity">
                    <span className="flex items-center gap-1 text-[10px] font-bold px-2 py-1 rounded-md bg-white text-slate-900 shadow-md">
                      <Eye className="w-3 h-3 text-sky-600" />
                      <span>Inspect</span>
                    </span>
                  </div>
                </div>

                {/* Card Content & Telemetry */}
                <div className="p-4 space-y-2">
                  <h3 className="font-bold text-sm text-slate-900 group-hover:text-sky-700 transition-colors line-clamp-1">
                    {study.title}
                  </h3>

                  <p className="text-xs text-slate-600 leading-relaxed line-clamp-2">
                    {study.description}
                  </p>

                  {/* Physics Telemetry Mini Strip */}
                  <div className="p-2 rounded-lg bg-sky-50/80 border border-sky-100 text-[11px] font-mono text-slate-700 space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="text-slate-500">Flow:</span>
                      <span className="font-bold text-sky-700">{study.telemetry.mach}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-slate-500">Aero Data:</span>
                      <span className="font-bold text-emerald-700">{study.telemetry.coefficients}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom Action */}
              <div className="px-4 pb-4 pt-1 flex items-center justify-between border-t border-slate-100 text-xs font-bold text-sky-600 group-hover:text-sky-700">
                <span className="flex items-center gap-1">
                  <span>View Details</span>
                  <ChevronRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                </span>
                <span className="text-[10px] font-mono text-slate-400">
                  {study.telemetry.solver}
                </span>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Section: What is CFD? */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.1 }}
        className="card-bright rounded-2xl border border-sky-200/90 p-6 space-y-4 bg-white/95 shadow-sm"
      >
        <div className="flex items-center gap-2.5 pb-3 border-b border-slate-200">
          <div className="w-9 h-9 rounded-lg bg-sky-100 text-sky-700 flex items-center justify-center shadow-2xs border border-sky-200">
            <Microscope className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-900">What is Computational Fluid Dynamics?</h2>
            <p className="text-xs text-slate-500">The underlying physics & numerical methods powering this platform</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-xs text-slate-600 leading-relaxed">
          <div className="space-y-2 p-3.5 rounded-xl bg-sky-50/70 border border-sky-200/80">
            <h3 className="font-bold text-sm text-slate-900 flex items-center gap-1.5">
              <Wind className="w-4 h-4 text-sky-600" />
              The Digital Wind Tunnel
            </h3>
            <p>
              <strong>Computational Fluid Dynamics (CFD)</strong> is the science of using numerical methods and Navier-Stokes partial differential equations to model fluid flow, pressure drop, turbulence dissipation, and heat transfer.
            </p>
          </div>

          <div className="space-y-2 p-3.5 rounded-xl bg-cyan-50/70 border border-cyan-200/80">
            <h3 className="font-bold text-sm text-slate-900 flex items-center gap-1.5">
              <Cpu className="w-4 h-4 text-cyan-600" />
              Navier-Stokes Equations
            </h3>
            <p>
              Instead of building expensive physical wind tunnel clay models, our computational engine solves mass, momentum, and energy conservation across boundary-layer polyhedral meshes.
            </p>
          </div>

          <div className="space-y-2 p-3.5 rounded-xl bg-purple-50/70 border border-purple-200/80">
            <h3 className="font-bold text-sm text-slate-900 flex items-center gap-1.5">
              <Brain className="w-4 h-4 text-purple-600" />
              AI Fourier Neural Operators
            </h3>
            <p>
              Augmented with Fourier Neural Operators (FNO) and Physics-Informed Neural Networks (PINN) to compute sub-second aerodynamic surrogate predictions with certified confidence metrics.
            </p>
          </div>
        </div>
      </motion.div>

      {/* Section: Core Capabilities Grid with Real Graphics Banners */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Zap className="w-4 h-4 text-sky-600" />
            <h2 className="text-base font-bold text-slate-900">Core Capabilities</h2>
          </div>
          <span className="text-xs text-slate-500 font-medium">Full-featured industrial aerodynamic engineering</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Card 1: CFD Simulation */}
          <div
            onClick={() => setPage('runner')}
            className="group card-bright hover:bg-sky-50/60 border border-sky-200 hover:border-sky-500 rounded-2xl p-5 transition-all duration-200 cursor-pointer flex flex-col justify-between bg-white shadow-xs"
          >
            <div className="space-y-3">
              <div className="w-full h-24 rounded-xl overflow-hidden border border-sky-200 relative bg-slate-900">
                <img
                  src="/src/assets/images/cfd_wind_tunnel_vehicle_1790163836534.jpg"
                  alt="CFD Solver Simulation"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute top-1.5 right-1.5 text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-sky-950/80 text-cyan-300">
                  OpenFOAM
                </span>
              </div>
              <h3 className="font-bold text-sm text-slate-900 group-hover:text-sky-700 transition-colors">
                CFD Simulation Solvers
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Run OpenFOAM and SU2 steady and transient solvers for external aerodynamics, internal conduit manifolds, and shockwave propagation.
              </p>
            </div>
            <div className="pt-4 flex items-center gap-1 text-[11px] font-bold text-sky-600">
              <span>Launch Runner</span>
              <ArrowRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
            </div>
          </div>

          {/* Card 2: 3D Visualization */}
          <div
            onClick={() => setPage('results')}
            className="group card-bright hover:bg-cyan-50/60 border border-cyan-200 hover:border-cyan-500 rounded-2xl p-5 transition-all duration-200 cursor-pointer flex flex-col justify-between bg-white shadow-xs"
          >
            <div className="space-y-3">
              <div className="w-full h-24 rounded-xl overflow-hidden border border-cyan-200 relative bg-slate-900">
                <img
                  src="/src/assets/images/cfd_transonic_shockwave_1790163852748.jpg"
                  alt="3D Visualization"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute top-1.5 right-1.5 text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-slate-950/80 text-amber-300">
                  Pressure -Cp
                </span>
              </div>
              <h3 className="font-bold text-sm text-slate-900 group-hover:text-cyan-700 transition-colors">
                3D Pressure & Streamlines
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Interactive 60 FPS velocity vector ribbons, surface pressure contours (-Cp), lambda shock boundaries, and rainbow scalar colormaps.
              </p>
            </div>
            <div className="pt-4 flex items-center gap-1 text-[11px] font-bold text-cyan-600">
              <span>Explore Viewport</span>
              <ArrowRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
            </div>
          </div>

          {/* Card 3: AI Analysis */}
          <div
            onClick={() => setPage('ai')}
            className="group card-bright hover:bg-purple-50/60 border border-purple-200 hover:border-purple-500 rounded-2xl p-5 transition-all duration-200 cursor-pointer flex flex-col justify-between bg-white shadow-xs"
          >
            <div className="space-y-3">
              <div className="w-full h-24 rounded-xl overflow-hidden border border-purple-200 relative bg-slate-900">
                <img
                  src="/src/assets/images/cfd_neural_flow_ai_1790163889547.jpg"
                  alt="AI Neural Analysis"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute top-1.5 right-1.5 text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-purple-950/80 text-purple-200">
                  12ms FNO
                </span>
              </div>
              <h3 className="font-bold text-sm text-slate-900 group-hover:text-purple-700 transition-colors">
                AI Physics Surrogates
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Fourier Neural Operators (FNO) and Physics-Informed Neural Networks for sub-second flow prediction and confidence metrics.
              </p>
            </div>
            <div className="pt-4 flex items-center gap-1 text-[11px] font-bold text-purple-600">
              <span>Open AI Studio</span>
              <ArrowRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
            </div>
          </div>

          {/* Card 4: Automated Reports */}
          <div
            onClick={() => setPage('reporting')}
            className="group card-bright hover:bg-emerald-50/60 border border-emerald-200 hover:border-emerald-500 rounded-2xl p-5 transition-all duration-200 cursor-pointer flex flex-col justify-between bg-white shadow-xs"
          >
            <div className="space-y-3">
              <div className="w-full h-24 rounded-xl overflow-hidden border border-emerald-200 relative bg-slate-900">
                <img
                  src="/src/assets/images/cfd_vortex_propeller_wake_1790163871792.jpg"
                  alt="Automated Reports"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute top-1.5 right-1.5 text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-emerald-950/80 text-emerald-200">
                  Polars & Excel
                </span>
              </div>
              <h3 className="font-bold text-sm text-slate-900 group-hover:text-emerald-700 transition-colors">
                Automated Reports & Polars
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Generate professional multi-worksheet Excel spreadsheets, VTK structured grid files, and aerodynamic compliance certificates.
              </p>
            </div>
            <div className="pt-4 flex items-center gap-1 text-[11px] font-bold text-emerald-600">
              <span>Generate Reports</span>
              <ArrowRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
            </div>
          </div>
        </div>
      </div>

      {/* Engineering Workflow Stepper */}
      <div className="card-bright rounded-2xl border border-sky-200 p-6 space-y-4 bg-white/95 shadow-sm">
        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
          <span>Standard Industrial CFD Workflow Pipeline</span>
          <span className="text-[10px] px-2 py-0.5 rounded-full bg-sky-100 text-sky-700 font-mono font-bold">
            4 STAGES
          </span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 text-xs">
          <div className="p-3.5 bg-white rounded-xl border border-sky-200 shadow-2xs space-y-1.5">
            <span className="font-mono text-[10px] text-sky-600 font-bold">STAGE 01</span>
            <h4 className="font-bold text-slate-900">Geometry & Mesh</h4>
            <p className="text-[11px] text-slate-600">Upload STL/OBJ or select airfoil. Inspect watertightness and boundary layers.</p>
          </div>

          <div className="p-3.5 bg-white rounded-xl border border-cyan-200 shadow-2xs space-y-1.5">
            <span className="font-mono text-[10px] text-cyan-600 font-bold">STAGE 02</span>
            <h4 className="font-bold text-slate-900">Physics & Inflow</h4>
            <p className="text-[11px] text-slate-600">Set Mach number, angle of attack, k-ω SST turbulence, and fluid density.</p>
          </div>

          <div className="p-3.5 bg-white rounded-xl border border-purple-200 shadow-2xs space-y-1.5">
            <span className="font-mono text-[10px] text-purple-600 font-bold">STAGE 03</span>
            <h4 className="font-bold text-slate-900">Solver Execution</h4>
            <p className="text-[11px] text-slate-600">Monitor logarithmic residual decay, mass flow balance, and Courant CFL stepping.</p>
          </div>

          <div className="p-3.5 bg-white rounded-xl border border-emerald-200 shadow-2xs space-y-1.5">
            <span className="font-mono text-[10px] text-emerald-600 font-bold">STAGE 04</span>
            <h4 className="font-bold text-slate-900">Telemetry & Export</h4>
            <p className="text-[11px] text-slate-600">Inspect lift/drag polars, evaluate AI surrogate models, and download Excel reports.</p>
          </div>
        </div>
      </div>

      {/* Interactive High-Resolution Aerodynamic Study Lightbox Modal */}
      <AnimatePresence>
        {selectedStudy && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/75 backdrop-blur-md animate-in fade-in duration-200">
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-white rounded-2xl shadow-2xl border border-sky-300 text-slate-800 flex flex-col"
            >
              {/* Modal Header */}
              <div className="p-4 sm:p-5 border-b border-slate-200 flex items-center justify-between sticky top-0 bg-white/95 backdrop-blur-md z-10">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-sky-100 text-sky-700 flex items-center justify-center font-bold">
                    <Wind className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="font-bold text-sm sm:text-base text-slate-900 leading-tight">
                      {selectedStudy.title}
                    </h3>
                    <div className="flex items-center gap-2 text-[11px] text-slate-500 font-mono">
                      <span>{selectedStudy.category}</span>
                      <span>•</span>
                      <span className="text-sky-600 font-bold">{selectedStudy.regime}</span>
                    </div>
                  </div>
                </div>

                <button
                  onClick={() => setSelectedStudy(null)}
                  className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 hover:text-slate-800 transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Modal Body with Large Graphic & Engineering Data */}
              <div className="p-4 sm:p-6 space-y-6">
                {/* Large Real Graphic Display */}
                <div className="relative aspect-video w-full rounded-xl overflow-hidden shadow-lg border border-slate-300 bg-slate-950">
                  <img
                    src={selectedStudy.imageSrc}
                    alt={selectedStudy.title}
                    className="w-full h-full object-cover"
                    referrerPolicy="no-referrer"
                  />
                  <div className="absolute bottom-3 right-3 px-3 py-1 rounded-md bg-slate-900/80 backdrop-blur-md border border-white/20 text-white text-[11px] font-mono">
                    {selectedStudy.telemetry.solver}
                  </div>
                </div>

                {/* Telemetry Stats Grid */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div className="p-3 rounded-xl bg-sky-50 border border-sky-200">
                    <div className="text-[10px] text-slate-500 font-medium">Reynolds Number</div>
                    <div className="text-xs sm:text-sm font-bold font-mono text-sky-800">
                      {selectedStudy.telemetry.reynolds}
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-cyan-50 border border-cyan-200">
                    <div className="text-[10px] text-slate-500 font-medium">Mach / Velocity</div>
                    <div className="text-xs sm:text-sm font-bold font-mono text-cyan-800">
                      {selectedStudy.telemetry.mach}
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200">
                    <div className="text-[10px] text-slate-500 font-medium">Aerodynamic Coefficients</div>
                    <div className="text-xs sm:text-sm font-bold font-mono text-emerald-800">
                      {selectedStudy.telemetry.coefficients}
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-purple-50 border border-purple-200">
                    <div className="text-[10px] text-slate-500 font-medium">CFD Solver Scheme</div>
                    <div className="text-xs sm:text-sm font-bold font-mono text-purple-800">
                      {selectedStudy.telemetry.solver}
                    </div>
                  </div>
                </div>

                {/* Description & Scientific Highlights */}
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Physics & Aerodynamic Analysis
                  </h4>
                  <p className="text-xs sm:text-sm text-slate-700 leading-relaxed">
                    {selectedStudy.description}
                  </p>

                  <div className="pt-2">
                    <h5 className="text-xs font-bold text-slate-800 mb-2">Key Flow Phenomena Observed:</h5>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {selectedStudy.highlights.map((highlight, hIdx) => (
                        <div key={hIdx} className="flex items-center gap-2 p-2 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-700">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                          <span>{highlight}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* Modal Footer Actions */}
              <div className="p-4 sm:p-5 border-t border-slate-200 bg-slate-50 flex items-center justify-between sticky bottom-0">
                <button
                  onClick={() => setSelectedStudy(null)}
                  className="px-4 py-2 rounded-xl border border-slate-300 text-slate-700 hover:bg-slate-200 text-xs font-semibold transition-colors cursor-pointer"
                >
                  Close
                </button>

                <button
                  onClick={() => handleLaunchStudy(selectedStudy)}
                  className="flex items-center gap-2 px-5 py-2 rounded-xl bg-gradient-to-r from-sky-600 to-sky-700 hover:from-sky-700 hover:to-sky-800 text-white text-xs font-bold shadow-md transition-all active:scale-95 cursor-pointer"
                >
                  <Rocket className="w-4 h-4" />
                  <span>Load into Workbench</span>
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Footer */}
      <footer className="pt-4 pb-2 border-t border-sky-200 text-center text-xs text-slate-500 flex flex-col sm:flex-row items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <CfdLogo size="xs" showText={true} />
        </div>
        <span>CFD Platform v0.1.0 • High-Performance Industrial Aerodynamics Workbench</span>
      </footer>
    </div>
  );
};

